[package]
name = "gateway-db"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
gateway-common = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
